version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: ./.circleci/build.sh 
      - run:
          name: Deploy lambdas
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ] ; then
              cd hello-world
              make deploy

workflows:
  version: 2
  build:
    jobs:
      - build 
