version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      
  deploy:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run:
          name: Deploy lambdas
          command: |
            sudo npm install -g serverless
            sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

            if [ "${CIRCLE_BRANCH}" = "master" ] ; then
              cd hello-world
              sls deploy --stage prod
            fi

            if [ "${CIRCLE_BRANCH}" = "develop"] ; then
              cd hello-world
              sls deploy --stage dev
            fi
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
