version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Create lambda layer
          command: | 
            cd layer
            export PKG_DIR="python"
            rm -rf ${PKG_DIR} && mkdir -p ${PKG_DIR}
            ls
            docker run --rm -v $(pwd):/foo -w /foo lambci/lambda:build-python3.7 pip install -r ./requirements.txt --no-deps -t ${PKG_DIR}
            cd .. 
            pwd
      - run:
          name: Deploy lambdas
          command: |
            pwd
            sudo npm install -g serverless
            sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

            if [ "${CIRCLE_BRANCH}" = "master" ] ; then
              sls deploy --stage prod
            fi
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
