version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      
  deploy:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run:
          name: Deploy lambdas
          command: |
            sudo npm install -g serverless
            sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

            if [ "${CIRCLE_BRANCH}" = "master" ] ; then
              cd layer
              source ./build_layer.sh
              cd ..
              pwd
              sls deploy --stage prod
            fi
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
